language: java

sudo: false

script: mvn clean install

before_install: 
  - git clone https://github.com/open-amdocs/zusammen-commons.git ~/builds/open-amdocs/zusammen-commons 
  - pushd ~/builds/open-amdocs/zusammen-commons
  - mvn clean install
  - popd 
  
cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8


  
